version: "3"

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpp-consumer:v1
    container_name: cpp-consumer
    restart: on-failure:5 # restart on failure, max 5 times
    environment:
      - KAFKA_BROKERS=172.17.0.1:9092
      - KAFKA_CONSUMER_GROUP=local
      - KAFKA_STATISTICS_INTERVAL_MS=60000
      - KAKFA_DO_CONFIG_DUMP=true
      - KAFKA_TOPIC=sample_topic
